### ISSUE TITLE
Manifest URL does not work

### ISSUE THREAD

**Issue by chrpow** [Larkinabout/fvtt-token-action-hud-template#3]
I would like to make a module for an RPG system (Shadowdark RPG), so I wanted to download this template to get started. Neither of the installation methods listed in the readme worked for me.

Method 1 instructs me to download "Token Action HUD Pathfinder 2." I assume this is a typo? I thought I was supposed to download the general template, not the PF2E module. Searching for "Template" in the Foundry module interface yielded nothing.

Method 2 gives a manifest URL `https://github.com/Larkinabout/fvtt-token-action-hud-template/releases/latest/download/module.json`. When I tried this, I got an error message saying there was no module at that URL 
![image](https://github.com/Larkinabout/fvtt-token-action-hud-template/assets/15185224/fdced9b5-7277-4054-b5ec-aaebe9d27466)

Is there any way to get the template installed? Is this still the best way to create a Token Action HUD module for a new system?

**Comment by Larkinabout** [comment]
Hi @chrpow,

This repos is not a published module, it's a starter template to copy, replace code and publish your own Token Action HUD system module. Everything, including the URLs listed in the manifest file and the README content, are just placeholders for your own code.

For additional info on creating your own Token Action HUD system module, check out: [Developing a System Module](https://github.com/Larkinabout/fvtt-token-action-hud-core/wiki/Developing-a-System-Module).
